apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-apps
resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml

configMapGenerator:
- name: sample-app-config
  literals:
    - WAVEFRONT_PROXY="localhost"
generatorOptions:
  disableNameSuffixHash: true